moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - X_Joint
    - Y_Joint
    - Z_Joint
    - Z_Rot_Joint
    - Cup_Joint

  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: gantry_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - X_Joint
    - Y_Joint
    - Z_Joint
    - Z_Rot_Joint
    - Cup_Joint


gantry_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - X_Joint
    - Y_Joint
    - Z_Joint
    - Z_Rot_Joint
    - Cup_Joint

  gains:
    X_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Y_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Z_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Z_Rot_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Cup_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

# moveit_sim_hw_interface:
#   joint_model_group: controllers_initial_group_
#   joint_model_group_pose: controllers_initial_pose_
# # Settings for ros_control control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - X_Joint
#     - Y_Joint
#     - Z_Joint
#     - Z_Rot_Joint
#     # - dummy_Joint
#     - Cup_Joint

#   sim_control_mode: 1  # 0: position, 1: velocity
# # Publish all joint states
# # Creates the /joint_states topic necessary in ROS
# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50

# controller_list:
#   - name: gantry_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#     - X_Joint
#     - Y_Joint
#     - Z_Joint
#     - Z_Rot_Joint
#     # - dummy_Joint
#     gains:
#       X_Joint:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Y_Joint:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Z_Joint:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Z_Rot_Joint:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       # dummy_Joint:
#       #   p: 100
#       #   d: 1
#       #   i: 1
#       #   i_clamp: 1

#   - name: cup_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#     - Cup_Joint
#     gains:
#       Cup_Joint:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1

# gantry_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#     - X_Joint
#     - Y_Joint
#     - Z_Joint
#     - Z_Rot_Joint
#     # - dummy_Joint

#  constraints:
#    goal_time: 0.6
#    stopped_velocity_tolerance: 0.0
#    X_Joint: {trajectory: 0.0, goal: 0.0}
#    Y_Joint: {trajectory: 0.0, goal: 0.0}
#    Z_Joint: {trajectory: 0.0, goal: 0.0}
#    Z_Rot_Joint: {trajectory: 0.0, goal: 0.0}
#   #  dummy_Joint: {trajectory: 0.0, goal: 0.0}

#  gains:
#    X_Joint: {p: 200, d: 1, i: 1, i_clamp: 1}
#    Y_Joint: {p: 300, d: 1, i: 1, i_clamp: 1}
#    Z_Joint: {p: 200, d: 1, i: 1, i_clamp: 1}
#    Z_Rot_Joint: {p: 200, d: 1, i: 1, i_clamp: 1}
#   #  dummy_Joint: {p: 200, d: 1, i: 1, i_clamp: 1}

  
# #  stop_trajectory_duration: 0.5
# #  state_publish_rate:  25
# #  action_monitor_rate: 10

# cup_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#     - Cup_Joint
#  constraints:
#    goal_time: 0.6
#    stopped_velocity_tolerance: 0
#    Cup_Joint: {trajectory: 0.0, goal: 0.0}

#  gains:
#    Cup_Joint: {p: 200, d: 1, i: 1, i_clamp: 1}



# # gantry_controller:
# #   type: position_controllers/JointTrajectoryController
# #   joints:
# #     - X_Joint
# #     - Y_Joint
# #     - Z_Joint
# #     - Z_Rot_Joint
# #     - Cup_Joint

# #   gains:
# #     X_Joint:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     Y_Joint:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     Z_Joint:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     Z_Rot_Joint:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     Cup_Joint:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1




